### ISSUE TITLE
Mega downloading is not working 

### ISSUE THREAD

**Issue by Niaz264** [majnurangeela/mirror-hunter-upstream#1] opened 2022-06-16 21:41 UTC
I'm getting this error while downloading from mega.. I added my mega credentials but It’s not working 

NameError: name 'MEGA_KEY' is not defined

**Comment by majnurangeela** [comment] 2022-06-17 10:17
OK It will be fixed

**Comment by majnurangeela** [comment] 2022-06-17 11:39
The issue is fixed ! Thanks for reporting.
Note: Make sure MEGAREST env is True in config.env

**Closed by majnurangeela** 2022-06-17 11:39 UTC
